name: idpconfgen
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - matplotlib=3
    - numpy=1
    - numba
    - pybind11
    - scipy
    - pip
    - tox
    - pip:
        - tox-conda
